### ISSUE TITLE
test and debug wandb for v0.10 dev branch

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#113]
### Goals
* check new implementation for wandb
* debug train.py

### Dataset
TO BE UPDATED

**Comment by initze** [comment]
## Instructions
### Run on small testset
`CUDA_VISIBLE_DEVICES=0 train --data_dir /isipd/projects/p_aicore_pf/initze/processing_training/RTS_testData_v1/ --config /isipd/projects/p_aicore_pf/initze/processing_training/RTS_testData_v1/config_run_test.yml -n debug_01 -wn debug01`

Error:

> [2024-04-29T08:59:28.644+02:00] uc2.train INFO: Training on cuda device
> running without learning rate scheduler
> Traceback (most recent call last):
>   File "/isipd/projects-noreplica/p_initze/anaconda3/envs/RTS_v010/bin/train", line 8, in <module>
>     sys.exit(main())
>   File "/isipd/projects/p_aicore_pf/initze/code/code_v010_dev/src/thaw_slump_segmentation/scripts/train.py", line 349, in main
>     Engine().run()
>   File "/isipd/projects/p_aicore_pf/initze/code/code_v010_dev/src/thaw_slump_segmentation/scripts/train.py", line 137, in __init__
>     wandb.init(project=args.wandb_project, name=args.wandb_name, config=self.config, entity='ml4earth')
> NameError: name 'wandb' is not defined

**Comment by initze** [comment]
completed with #116
