### ISSUE TITLE
ensembling fails when empty

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#118]
```
(RTS_v010) initze@pd-dgx-a100:/isipd/projects/p_aicore_pf/initze/code/code_v010_dev$ process_03_ensemble 
Running ensembling with GPU!
Start running ensemble with 15 jobs!
Target ensemble name: RTS_v6_ensemble_v2
Source model output ['RTS_v6_tcvis', 'RTS_v6_notcvis']
Loading results 0.4
0it [00:00, ?it/s]
Merging results
Traceback (most recent call last):
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/RTS_v010/bin/process_03_ensemble", line 5, in <module>
    from thaw_slump_segmentation.scripts.process_03_ensemble import main
  File "/isipd/projects/p_aicore_pf/initze/code/code_v010_dev/src/thaw_slump_segmentation/scripts/process_03_ensemble.py", line 114, in <module>
    merged_gdf = gpd.pd.concat(out)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/RTS_v010/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/RTS_v010/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 445, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/RTS_v010/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 507, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
(RTS_v010) initze@pd-dgx-a100:/isipd/projects/p_aicore_pf/initze/code/code_v010_dev$ 
```

**Comment by initze** [comment]
additional minor issue

> /isipd/projects/p_aicore_pf/initze/code/code_v010_dev/src/thaw_slump_segmentation/scripts/process_03_ensemble.py:118: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
>   merged_gdf = gpd.pd.concat(out)
