### ISSUE TITLE
loss function bug

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#15]
using loss function
"SoftBCEWithLogitsLoss" causes the following crash

Config:
`loss_function: SoftBCEWithLogitsLoss`

Output:
```
[2021-11-17T09:06:27.267+01:00] uc2.train INFO: Training on cuda device
[2021-11-17T09:06:29.518+01:00] uc2.train INFO: Starting phase "Training"
Traceback (most recent call last):
  File "train.py", line 301, in <module>
    Engine().run()
  File "train.py", line 135, in run
    self.loss_function = create_loss(scoped_get('loss_function', phase, self.config)).to(self.dev)
  File "/isipd/projects/Response/GIS_RS_projects/dgx_initze/training_multi/lib/models/__init__.py", line 69, in create_loss
    return losses_dict[name](mode=losses.BINARY_MODE)
TypeError: __init__() got an unexpected keyword argument 'mode'
```

FocalLoss and DiceLoss are working

**Comment by khdlr** [comment]
That's odd, it seems the interface provided by the `segmentation_models_pytorch` package is not uniform for all loss functions.
