### ISSUE TITLE
prepare data crash on PlanetScene

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#28]
prepare_data.py script is crashing on PlanetScene

* setup_raw_daty.py is working!
  * does not contain tiles subdir!
* Processing to h5 is crashing
* h5 file and subdir is beeing created but not filled -

**Comment by initze** [comment]
![grafik](https://user-images.githubusercontent.com/4864803/159217677-9bb39d42-2c5f-40d5-9cad-c830170554b1.png)

**setup_raw_data**
```
[2022-03-21T08:04:32.982+01:00] uc2.setup_raw_data.20200814_044132_1026.ee INFO: > Processing /isipd/projects/p_aicore_pf/initze/processing_training/slumps/input/20200814_044132_1026/20200814_044132_1026_ee_tmp.tif [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
[2022-03-21T08:04:41.930+01:00] uc2.setup_raw_data.20200814_044132_1026.utils INFO: Called `$CONDA_PREFIX/bin/gdalwarp -te 563637.0 8370723.0 577581.0 8381652.0 -tr 3.0 3.0 -r cubic -t_srs EPSG:32649 -co COMPRESS=DEFLATE /isipd/projects/p_aicore_pf/initze/processing_training/slumps/auxiliary/ArcticDEM/elevation.vrt /isipd/projects/p_aicore_pf/initze/processing_training/slumps/input/20200814_044132_1026/relative_elevation.tif`
[2022-03-21T08:04:41.931+01:00] uc2.setup_raw_data.20200814_044132_1026.utils INFO: > Creating output file that is 4648P x 3643L.
[2022-03-21T08:04:41.931+01:00] uc2.setup_raw_data.20200814_044132_1026.utils INFO: > Processing /isipd/projects/p_aicore_pf/initze/processing_training/slumps/auxiliary/ArcticDEM/elevation.vrt [1/1] : 0Using internal nodata values (e.g. 0) for image /isipd/projects/p_aicore_pf/initze/processing_training/slumps/auxiliary/ArcticDEM/elevation.vrt.
[2022-03-21T08:04:41.931+01:00] uc2.setup_raw_data.20200814_044132_1026.utils INFO: > Copying nodata values from source /isipd/projects/p_aicore_pf/initze/processing_training/slumps/auxiliary/ArcticDEM/elevation.vrt to destination /isipd/projects/p_aicore_pf/initze/processing_training/slumps/input/20200814_044132_1026/relative_elevation.tif.
[2022-03-21T08:04:41.931+01:00] uc2.setup_raw_data.20200814_044132_1026.utils INFO: > ...10...20...30...40...50...60...70...80...90...100 - done.
[2022-03-21T08:04:52.225+01:00] uc2.setup_raw_data.20200814_044132_1026.utils INFO: Called `$CONDA_PREFIX/bin/gdalwarp -te 563637.0 8370723.0 577581.0 8381652.0 -tr 3.0 3.0 -r cubic -t_srs EPSG:32649 -co COMPRESS=DEFLATE /isipd/projects/p_aicore_pf/initze/processing_training/slumps/auxiliary/ArcticDEM/slope.vrt /isipd/projects/p_aicore_pf/initze/processing_training/slumps/input/20200814_044132_1026/slope.tif`
[2022-03-21T08:04:52.225+01:00] uc2.setup_raw_data.20200814_044132_1026.utils INFO: > Creating output file that is 4648P x 3643L.
[2022-03-21T08:04:52.225+01:00] uc2.setup_raw_data.20200814_044132_1026.utils INFO: > Processing /isipd/projects/p_aicore_pf/initze/processing_training/slumps/auxiliary/ArcticDEM/slope.vrt [1/1] : 0Using internal nodata values (e.g. 0) for image /isipd/projects/p_aicore_pf/initze/processing_training/slumps/auxiliary/ArcticDEM/slope.vrt.
[2022-03-21T08:04:52.225+01:00] uc2.setup_raw_data.20200814_044132_1026.utils INFO: > Copying nodata values from source /isipd/projects/p_aicore_pf/initze/processing_training/slumps/auxiliary/ArcticDEM/slope.vrt to destination /isipd/projects/p_aicore_pf/initze/processing_training/slumps/input/20200814_044132_1026/slope.tif.
[2022-03-21T08:04:52.226+01:00] uc2.setup_raw_data.20200814_044132_1026.utils INFO: > ...10...20...30...40...50...60...70...80...90...100 - done.
[2022-03-21T08:05:01.706+01:00] uc2.setup_raw_data.20200814_044132_1026 INFO: rename: skipped
[2022-03-21T08:05:01.707+01:00] uc2.setup_raw_data.20200814_044132_1026 INFO: label: success
[2022-03-21T08:05:01.707+01:00] uc2.setup_raw_data.20200814_044132_1026 INFO: ndvi: success
[2022-03-21T08:05:01.707+01:00] uc2.setup_raw_data.20200814_044132_1026 INFO: tcvis: success
[2022-03-21T08:05:01.707+01:00] uc2.setup_raw_data.20200814_044132_1026 INFO: rel_dem: success
[2022-03-21T08:05:01.707+01:00] uc2.setup_raw_data.20200814_044132_1026 INFO: slope: success
[2022-03-21T08:05:01.707+01:00] uc2.setup_raw_data.20200814_044132_1026 INFO: mask: success
[2022-03-21T08:05:01.707+01:00] uc2.setup_raw_data.20200814_044132_1026 INFO: move: success
```

**Comment by initze** [comment]
`python prepare_data.py --data_dir $PROCESSING_DIR --tile_size 1024x1024 --tile_overlap 128;`

* tiles is being created
* subdirs as well
* h5 structure is created
* then crash

```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "prepare_data.py", line 215, in main_function
    with rio.open(mask_from_img(img)) as raster:
  File "prepare_data.py", line 80, in mask_from_img
    assert mask_path.exists()
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "prepare_data.py", line 302, in <module>
    Parallel(n_jobs=args.n_jobs)(delayed(main_function)(dataset, args, log_path) for dataset in datasets)
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AssertionError
```

```
Traceback (most recent call last):
  File "prepare_data.py", line 302, in <module>
    Parallel(n_jobs=args.n_jobs)(delayed(main_function)(dataset, args, log_path) for dataset in datasets)
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/pd/initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "prepare_data.py", line 215, in main_function
    with rio.open(mask_from_img(img)) as raster:
  File "prepare_data.py", line 80, in mask_from_img
    assert mask_path.exists()
AssertionError
```
