### ISSUE TITLE
Memory piining issue

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#53]
**raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly**

* trying to change pytorch version
```
ssh://initze@pd-dgx-a100.dmawi.de:22/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/bin/python -u /isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py --data_dir data/planet --log_dir logs -c config_example.yml
[2023-05-24T11:18:07.923+02:00] uc2.train INFO: Training on cuda device
running with 'StepLR' learning rate scheduler with step_size = 10 and gamma = 0.1
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 2
2
wandb: You chose 'Use an existing W&B account'
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: f25ba45cbaa69de820fcba1f159b253def10888f

wandb: Appending key for api.wandb.ai to your netrc file: /home/pd/initze/.netrc
wandb: Tracking run with wandb version 0.15.3
wandb: Run data is saved locally in /isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/wandb/run-20230524_111829-dh81jiu4
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run revived-universe-1
wandb: ⭐️ View project at https://wandb.ai/ingmarnitze_team/RTS%20Sentinel2
wandb: 🚀 View run at https://wandb.ai/ingmarnitze_team/RTS%20Sentinel2/runs/dh81jiu4
[2023-05-24T11:18:30.374+02:00] uc2.train INFO: Starting phase "Training"
[2023-05-24T11:18:30.495+02:00] uc2.train INFO: Epoch 1 - Training Started
100%|███████████████████████████████████████████| 57/57 [00:12<00:00,  4.65it/s]
[2023-05-24T11:18:42.745+02:00] uc2.train INFO: Epoch 1 - Training Metrics: {'Accuracy': 0.9821200966835022, 'Precision': 0.0, 'Recall': 0.0, 'F1': nan, 'IoU': 0.0, 'Loss': 0.013796459883451462}
[2023-05-24T11:18:43.719+02:00] uc2.train INFO: Epoch 1 - Validation Started
  0%|                                                     | 0/9 [00:00<?, ?it/s]Exception in thread Thread-1:
Traceback (most recent call last):
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    idx, data = r
ValueError: not enough values to unpack (expected 2, got 0)

  0%|                                                     | 0/9 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py", line 378, in <module>
    Engine().run()
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py", line 166, in run
    self.val_epoch(data_loader, key)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py", line 239, in val_epoch
    for iteration, (raw_img, raw_target, metadata) in enumerate(tqdm(val_loader)):
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 349, in __iter__
    self._iterator._reset(self)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 852, in _reset
    data = self._get_data()
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1029, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 
wandb: Run history:
wandb:         epoch ▁
wandb:  trn/Accuracy ▁
wandb:       trn/IoU ▁
wandb:      trn/Loss ▁
wandb: trn/Precision ▁
wandb:    trn/Recall ▁
wandb: 
wandb: Run summary:
wandb:         epoch 1
wandb:  trn/Accuracy 0.98212
wandb:        trn/F1 nan
wandb:       trn/IoU 0.0
wandb:      trn/Loss 0.0138
wandb: trn/Precision 0.0
wandb:    trn/Recall 0.0
wandb: 
wandb: 🚀 View run revived-universe-1 at: https://wandb.ai/ingmarnitze_team/RTS%20Sentinel2/runs/dh81jiu4
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230524_111829-dh81jiu4/logs

Process finished with exit code 1

```

**Comment by initze** [comment]
Update led to new issue

```
ssh://initze@pd-dgx-a100.dmawi.de:22/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/bin/python -u /isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py --data_dir data/planet --log_dir logs -c config_example.yml
[2023-05-24T11:36:30.542+02:00] uc2.train INFO: Training on cuda device
running with 'StepLR' learning rate scheduler with step_size = 10 and gamma = 0.1
wandb: Currently logged in as: ingmarnitze (ingmarnitze_team). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.3
wandb: Run data is saved locally in /isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/wandb/run-20230524_113632-fsl8a6ip
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run dry-cloud-2
wandb: ⭐️ View project at https://wandb.ai/ingmarnitze_team/RTS%20Sentinel2
wandb: 🚀 View run at https://wandb.ai/ingmarnitze_team/RTS%20Sentinel2/runs/fsl8a6ip
[2023-05-24T11:36:33.400+02:00] uc2.train INFO: Starting phase "Training"
[2023-05-24T11:36:33.523+02:00] uc2.train INFO: Epoch 1 - Training Started
100%|███████████████████████████████████████████| 57/57 [00:21<00:00,  2.64it/s]
[2023-05-24T11:36:55.105+02:00] uc2.train INFO: Epoch 1 - Training Metrics: {'Accuracy': 0.9916985630989075, 'Precision': 0.0, 'Recall': 0.0, 'F1': nan, 'IoU': 0.0, 'Loss': 0.007874753326177597}
[2023-05-24T11:36:56.073+02:00] uc2.train INFO: Epoch 1 - Validation Started
100%|█████████████████████████████████████████████| 9/9 [00:00<00:00, 19.22it/s]
[2023-05-24T11:36:56.545+02:00] uc2.train INFO: Epoch 1 - Validation Metrics: {'Accuracy': 0.9643468856811523, 'Precision': nan, 'Recall': 0.0, 'F1': nan, 'IoU': 0.0, 'Loss': 3.413618564605713}
Traceback (most recent call last):
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py", line 378, in <module>
    Engine().run()
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py", line 166, in run
    self.val_epoch(data_loader, key)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py", line 272, in val_epoch
    self.log_images(val_outputs)
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py", line 311, in log_images
    fill=0, outline=255, width=3)
TypeError: polygon() got an unexpected keyword argument 'width'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 
wandb: Run history:
wandb:         epoch ▁
wandb:  trn/Accuracy ▁
wandb:       trn/IoU ▁
wandb:      trn/Loss ▁
wandb: trn/Precision ▁
wandb:    trn/Recall ▁
wandb:  val/Accuracy ▁
wandb:       val/IoU ▁
wandb:      val/Loss ▁
wandb:    val/Recall ▁
wandb: 
wandb: Run summary:
wandb:         epoch 1
wandb:  trn/Accuracy 0.9917
wandb:        trn/F1 nan
wandb:       trn/IoU 0.0
wandb:      trn/Loss 0.00787
wandb: trn/Precision 0.0
wandb:    trn/Recall 0.0
wandb:  val/Accuracy 0.96435
wandb:        val/F1 nan
wandb:       val/IoU 0.0
wandb:      val/Loss 3.41362
wandb: val/Precision nan
wandb:    val/Recall 0.0
wandb: 
wandb: 🚀 View run dry-cloud-2 at: https://wandb.ai/ingmarnitze_team/RTS%20Sentinel2/runs/fsl8a6ip
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230524_113632-fsl8a6ip/logs

Process finished with exit code 1

```
