### ISSUE TITLE
training crash

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#55]
More detailed info will follow shortly
```
ssh://initze@pd-dgx-a100.dmawi.de:22/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/bin/python -u /isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py --data_dir data/planet --log_dir logs -c config_example_train.yml
[2023-05-25T09:56:45.548+02:00] uc2.train INFO: Training on cuda device
running with 'ExponentialLR' learning rate scheduler with gamma = 0.9
wandb: Currently logged in as: ingmarnitze (ingmarnitze_team). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.3
wandb: Run data is saved locally in /isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/wandb/run-20230525_095647-e4kz1vns
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run devout-dragon-14
wandb: ⭐️ View project at https://wandb.ai/ingmarnitze_team/RTS%20Sentinel2
wandb: 🚀 View run at https://wandb.ai/ingmarnitze_team/RTS%20Sentinel2/runs/e4kz1vns
[2023-05-25T09:56:48.296+02:00] uc2.train INFO: Starting phase "Training"
[2023-05-25T09:56:49.026+02:00] uc2.train INFO: Epoch 1 - Training Started
 69%|████████████████████████████▍            | 506/729 [01:58<00:52,  4.28it/s]
Traceback (most recent call last):
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py", line 378, in <module>
    Engine().run()
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py", line 162, in run
    self.train_epoch(data_loader)
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_konrad/train.py", line 195, in train_epoch
    for iteration, (img, target, metadata) in enumerate(progress):
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 143, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 143, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 172, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 163, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: torch.cat(): input types can't be cast to the desired output type Byte

wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.

```

**Comment by initze** [comment]
Test `data_threads: 1`
* makes loading slow
Same error!

**Comment by initze** [comment]
It seems to be a data issues with dataset:
4751812_3973218_2021-08-01_1026
* strange size and data - much bigger that the other datasets
