### ISSUE TITLE
Bug: crashing build_datacubes with empty geometries

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#68]
building datacubes crashing

### Error message
```
 File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/rasterio/env.py", line 387, in wrapper
    return f(*args, **kwds)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/rasterio/features.py", line 321, in rasterize
    raise ValueError('No valid geometry objects found for rasterize')
ValueError: No valid geometry objects found for rasterize
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build_datacubes.py", line 368, in <module>
    [(f, ) for f in planet_files])
  File "build_datacubes.py", line 340, in run_jobs
    Parallel(n_jobs=n_jobs)(delayed(function)(*args, out_dir) for args in args_list)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: No valid geometry objects found for rasterize
```

**Comment by khdlr** [comment]
I guess this happens because the code is trying to burn masks for a region where there are no masks. A good solutino here would be to output an empty (all zero) mask in this case and warn the user that this datacube has no targets.

Is this for inference datacubes or for training cubes?

**Comment by initze** [comment]
Done!
