### ISSUE TITLE
Build datacubes crasheds on empty label layer

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#72]
Need to handle empty label shapefiles!
* read number of features, write empty file.

```
Traceback (most recent call last):
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_inference/thaw-slump-segmentation/build_datacubes.py", line 362, in <module>
    run_jobs(build_planet_cube, args.n_jobs, out_dir,
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_inference/thaw-slump-segmentation/build_datacubes.py", line 339, in run_jobs
    Parallel(n_jobs=n_jobs)(delayed(function)(*args, out_dir) for args in args_list)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09_310/lib/python3.10/site-packages/joblib/parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09_310/lib/python3.10/site-packages/joblib/parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_inference/thaw-slump-segmentation/build_datacubes.py", line 65, in build_planet_cube
    scene.save(out_dir / f'{scene.id}.nc', compression=args.no_compression)
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_inference/thaw-slump-segmentation/lib/data/base.py", line 126, in save
    xarray_ds = self.to_xarray()
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_inference/thaw-slump-segmentation/lib/data/base.py", line 99, in to_xarray
    ds = xr.Dataset({
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_inference/thaw-slump-segmentation/lib/data/base.py", line 100, in <dictcomp>
    type(ly).__name__: ly.get_raster_data(self)
  File "/isipd/projects/p_aicore_pf/initze/code/code_dev_inference/thaw-slump-segmentation/lib/data/mask.py", line 16, in get_raster_data
    mask = rasterize(self.geometries.to_crs(scene.crs),
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09_310/lib/python3.10/site-packages/rasterio/env.py", line 401, in wrapper
    return f(*args, **kwds)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09_310/lib/python3.10/site-packages/rasterio/features.py", line 331, in rasterize
    raise ValueError('No valid geometry objects found for rasterize')
ValueError: No valid geometry objects found for rasterize
```

**Comment by khdlr** [comment]
It's a bit annoying that rasterio cannot handle this edge-case by itself, but should be easy to address.

Out of curiosity: What's the use-case here? Including regions where we know to be RTS-free in order to reduce false positives?

**Comment by initze** [comment]
> Out of curiosity: What's the use-case here? Including regions where we know to be RTS-free in order to reduce false positives?
exactly. I think I already pushed this somewhere. I am also working on training data, augemntation e.g. wasnt in the new v09 version implemented yet

**Comment by initze** [comment]
fixed with https://github.com/initze/thaw-slump-segmentation/commit/981e0e5e8fcb812d1ea05e524d0dc231b3b57952
