### ISSUE TITLE
s2 build_datacube crash

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#75]
```
(aicore_v09_310_v2) initze@linux1:/isipd/projects/p_aicore_pf/initze/code/data_loading_update/thaw-slump-segmentation$ time python build_datacubes.py --data_dir data_debug --mode s2 --n_jobs 1
[2023-12-08T16:27:59.652+01:00] uc2.setup_raw_data INFO: ################################
[2023-12-08T16:27:59.652+01:00] uc2.setup_raw_data INFO: # Starting Building Data Cubes #
[2023-12-08T16:27:59.652+01:00] uc2.setup_raw_data INFO: ################################
Traceback (most recent call last):
  File "/isipd/projects/p_aicore_pf/initze/code/data_loading_update/thaw-slump-segmentation/build_datacubes.py", line 389, in <module>
    targets, scenes, sites = load_annotations(shapefile_root)
  File "/isipd/projects/p_aicore_pf/initze/code/data_loading_update/thaw-slump-segmentation/build_datacubes.py", line 295, in load_annotations
    targets = pd.concat(targets).to_crs('EPSG:3995').reset_index(drop=True)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09_310_v2/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09_310_v2/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore_v09_310_v2/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

**Comment by initze** [comment]
Looks like a "user error" :)
perhaps calling that could be slightly adapted or better documented
