### ISSUE TITLE
v0.8.1 dev - setup_raw_data crashed with new PSScenes (udm2 only)

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#87]
data_pre_processing/utils.py
* change checks for udm and udm data
```[2024-02-07T11:06:47.757+01:00] uc2.setup_raw_data INFO: ###########################
[2024-02-07T11:06:47.757+01:00] uc2.setup_raw_data INFO: # Starting Raw Data Setup #
[2024-02-07T11:06:47.757+01:00] uc2.setup_raw_data INFO: ###########################
[2024-02-07T11:06:50.875+01:00] uc2.setup_raw_data.20230704_200321_12_24b3 INFO: Starting preprocessing 20230704_200321_12_24b3
[2024-02-07T11:06:50.877+01:00] uc2.setup_raw_data.20230704_200321_12_24b3.utils INFO: No "_clip" naming found. Assume renaming not necessary
Traceback (most recent call last):
  File "setup_raw_data.py", line 120, in <module>
    Parallel(n_jobs=args.n_jobs)(delayed(preprocess_directory)(image_dir, args, log_path, args.nolabel) for image_dir in dir_list)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/isipd/projects-noreplica/p_initze/anaconda3/envs/aicore/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "setup_raw_data.py", line 71, in preprocess_directory
    success_state['ndvi'] = make_ndvi_file(image_dir)
  File "/isipd/projects/p_aicore_pf/initze/code/code_081_dev/lib/data_pre_processing/utils.py", line 62, in make_ndvi_file
    images = get_mask_images(image_directory, images=['_SR.tif'])
  File "/isipd/projects/p_aicore_pf/initze/code/code_081_dev/lib/data_pre_processing/utils.py", line 86, in get_mask_images
    udm_file = [f for f in flist if udm in f][0]
IndexError: list index out of range```

**Comment by initze** [comment]
fixed with [d450ade](https://github.com/initze/thaw-slump-segmentation/commit/d450ade4450846da7b380f9b60bd3663258d9fbf)
